### ISSUE TITLE
Layout must have header, a main section and a footer

### ISSUE THREAD

**Issue by jterrazz** [jterrazz/42-hypertube#32]

**Comment by abbensid** [comment]
Header material rm

**Comment by jterrazz** [comment]
<img width="747" alt="Screenshot 2019-11-25 at 07 35 53" src="https://user-images.githubusercontent.com/18480834/69517868-46580880-0f56-11ea-8364-2b20a38472b2.png">

**Comment by jterrazz** [comment]
- [ ] Check the main section meets this conditions

**Comment by abbensid** [comment]
[https://stackoverflow.com/questions/20470345/should-the-header-and-footer-tags-be-inside-the-main-tag/20470513](url)

**Comment by abbensid** [comment]
https://stackoverflow.com/questions/20470345/should-the-header-and-footer-tags-be-inside-the-main-tag/20470513
