### ISSUE TITLE
Use same image

### ISSUE THREAD

**Issue by jterrazz** [jterrazz/42-hypertube#39]
<img width="1164" alt="Screenshot 2019-11-16 at 15 54 26" src="https://user-images.githubusercontent.com/18480834/68995111-67e82e80-088a-11ea-8b5b-f94f2941f495.png">

**Comment by jterrazz** [comment]
@abbensid Malheureusement c'est YTS qui me renvoie la mauvaise image. Je te propose que soit:
- on laisse l'image comme ca
- soit on utilise `poster_image` pour cette partie

**Comment by abbensid** [comment]
c'est réglé, j'ai ajoute une requete pour le premier film de chaque source.
