### ISSUE TITLE
check subtitles

### ISSUE THREAD

**Issue by jterrazz** [jterrazz/42-hypertube#47]

**Comment by abbensid** [comment]
![Screen Shot 2019-11-21 at 6 54 45 PM](https://user-images.githubusercontent.com/24206784/69363491-e41ab180-0c90-11ea-8da1-61740874a48e.png)
![Screen Shot 2019-11-21 at 6 54 57 PM](https://user-images.githubusercontent.com/24206784/69363492-e4b34800-0c90-11ea-8eb6-95cc6dc16acc.png)

**Comment by abbensid** [comment]
Put back the old subtitles methods
