### ISSUE TITLE
Put same input conditions for all forms

### ISSUE THREAD

**Issue by jterrazz** [jterrazz/42-hypertube#5]
- [x] file size
- [x] form conditions
- [x] photo size 10mb
- [x] firstName length min = 3, max = 42
- [x] lastName length min = 3, max = 42
- [x] username length min = 3, max = 42, matches(/^[a-zA-Z0-9]+$/) ??
- [x] comment length min = 5, max = 150 ??
- number of comments per film per user {user, comment <=10 / film } ??
- [x] email : yup.string().email() (using joi on server but it's probably the same)
- [x] password length min = 8, max 100

**Comment by abbensid** [comment]
[] - username length min = 3, max = 42
[] - firstName length min = 3, max = 42
[] - lastName length min = 3, max = 42
[] - email ?
[] - photo size 10mb
[] - password length min = 8, max ?
