### ISSUE TITLE
CUSTOM TORRENT

### ISSUE THREAD

**Issue by abbensid** [jterrazz/42-hypertube#57]
- [ ] Client (form to send torrent + view)
- [x] API: Add support for custom trackers

**Comment by jterrazz** [comment]
The /torrent/:hash/stream now supports trackers inside the query (array of trackers supported).
```javascript
#Example
http://localhost:3000/torrent/XXX/stream?tr=__TRACKER_A__&tr=__TRACKER_B__
```

We only need two useful data from a `torrent` or a `magnet link`: The hash and the trackers.
https://www.npmjs.com/package/parse-torrent
