### ISSUE TITLE
Complete registration

### ISSUE THREAD

**Issue by jterrazz** [jterrazz/42-hypertube#64]
In case of 3rd party

**Comment by abbensid** [comment]
![Screen Shot 2019-11-29 at 2 13 46 PM](https://user-images.githubusercontent.com/24206784/69871263-9adee900-12b2-11ea-942f-6c530682813e.png)

**Comment by jterrazz** [comment]
- [ ] Client force to stay on page
- [ ] Client UI show `must complete XXX`
