### ISSUE TITLE
Error Firefox

### ISSUE THREAD

**Issue by abbensid** [jterrazz/42-hypertube#70]
- [ ] 1

![Screen Shot 2019-12-04 at 3.06.43 PM.png](https://images.zenhubusercontent.com/5a0ad2818a75884b9087577e/933834e8-d8e5-4833-bdb6-7d85608d5e7c)

https://github.com/zeit/next.js/issues/4456
https://github.com/zeit/next.js/issues/1109

**Comment by jterrazz** [comment]
On peut les laisser les erreurs console dans avec `yarn dev`, faut juste corriger celles avec `yarn build` et `yarn start`

**Comment by jterrazz** [comment]
La connexion interrompue c'est normal, c'est le hot reload qui fait ca des fois
